### ISSUE TITLE
Enable to Delete Text Records in Edit Records Modal

### ISSUE THREAD

**Issue by eduramme** [blockful-io/external-resolver-dapp#117]
## Bug Report

The user is unable to delete a text record once it is set in the Edit Records modal. After attempting to delete the record, the backend does not modify the field, and the record remains in the list.

### Current behavior

The text record remains in the list and is not deleted.

### Expected behavior

The text record should be deleted and removed from the list it the user leaves it empty.

### Steps to reproduce

1. Navigate to the Edit Records modal.
2. Set a text record.
3. Attempt to delete the text record. (setting an empty field)
4. Observe that the text record is not deleted and remains in the list.

### Related code
EditRecordsModal

### Other info

https://github.com/blockful-io/external-resolver-dapp/pull/97#pullrequestreview-2199693849

**Comment by alextnetto** [comment]
Thanks for describing this bug @eduramme ! Small correction:

> The user is unable to delete a text record once it is set in the Edit Records modal. After attempting to delete the record, the blockchain does not modify the fiel, and the record remains in the list.

Here you are actually changing the record on the gateway (a database), not the blockchain.

**Comment by alextnetto** [comment]
@pikonha Can you test if this is enabled in the backend? If it's not able to change a record to an empty value, please create an issue to enable that in the backend.

**Comment by lgahdl** [comment]
Found the bug (it was a front end bug):

line 412

![Image](https://github.com/user-attachments/assets/4d22a51f-169d-4e11-afdc-2ca84cc6c909)
