### ISSUE TITLE
feat: manage resolver in domain page

### ISSUE THREAD

**Issue by alextnetto** [blockful-io/external-resolver-dapp#125]
### Describe the Feature Request

The user should be able to see what resolver it's using and also change the resolver from the current domain on the domains page.

See what resolver is being used: Maybe that's available in the subgraph query? Or also asking the universal resolver to the the resolver based on the DNS encoded name.

Edit resolver: This should be a transaction to the registry, changing the resolver related to the name.

### Design 
The Domain Page will present the Resolver Address and the user will be able to click in the display and open a modal, the modal will enable to edit and save a new Resolver Address.

**Comment by pikonha** [comment]
The function to change the domain's resolver is from the [ENSRegistry](https://github.com/ensdomains/ens-contracts/blob/staging/contracts/registry/ENSRegistry.sol#L103)

**Comment by pikonha** [comment]
I'm able to see the `edit` buttons even for domains I don't own or either with the wallet unconnected

**Comment by alextnetto** [comment]
Moving it back to in progress. I'm the owner of the name, but I'm not being able to change the resolver.



![Image](https://github.com/user-attachments/assets/f3770fdb-7671-4f73-a005-cf1194bf463e)

**Comment by pikonha** [comment]
Although I'm able to change a resolver of a domain I own, it requires a manual page refresh for the UI to update.

I'm still able to see the edit button of a domain I don't own ([link](https://dev-nameful.vercel.app/domains/alek.eth))
![Image](https://github.com/user-attachments/assets/cdc4ac4d-d5ea-49e7-95bc-fd9a03035828)

I'm unable to see one of my domains ([link](https://dev-nameful.vercel.app/domains/blockful-749.eth))
![Image](https://github.com/user-attachments/assets/e1bc25bc-f57f-4e7f-a2f5-f934830257b4)
![Image](https://github.com/user-attachments/assets/33fd091a-1e13-4940-8394-2f2f797329c2)

**Comment by pikonha** [comment]
apparently, it will be sorted by #146
