### ISSUE TITLE
feat: Add icons for coins besides ETH

### ISSUE THREAD

**Issue by FrancoAguzzi** [blockful-io/external-resolver-dapp#127]
## Describe the feature
Whenever visiting one domain page, this domain might have a list of addresses registered as the addresses for multiple networks such as BTC, ARB, etc.

## Preferred solution
Nowadays we use ETH icon to represent all of these addresses, take a look at the image below:

![Image](https://github.com/user-attachments/assets/d222d3cc-cffa-4a85-96b4-2c443a3e9797)

We want to show the correct icons for each coin from now on!

## Definition of done

- [x] Gather icons for each currency address displayed
- [x] Test it for every network possible and generate fallback to non-iconed networks (you could use a Thorin EnvelopeSVG)

**Comment by FrancoAguzzi** [comment]
Once this issue is resolved let's remove this const from the project:

`export const cryptocurrenciesToSymbol: { [k: string]: string } = {`

**Comment by eduramme** [comment]
<img width="1401" alt="image" src="https://github.com/user-attachments/assets/5bc96bba-304d-44cb-83ac-de856352bb34">

**Comment by pikonha** [comment]
I'm unable to set the addresses on a DB domain nor in Arb.

![Image](https://github.com/user-attachments/assets/6f9facb0-00bf-4c34-88e0-495ab7e52200)
![Image](https://github.com/user-attachments/assets/37143e5b-a6a4-4162-a9e4-414e65fadeb8)
![Image](https://github.com/user-attachments/assets/b782686c-68a3-435b-978d-416ab9e2945f)

and also the only address fields on the profile edit are OP, Arb, ETH and BTC. is that expected?

couldn't test this feature.

**Comment by eduramme** [comment]
@pikonha We're only supporting OP, Arb, ETH and BTC when editing profile records.

It seems like the issue with the address records not changing is related to the backend. The handleDBStorage function isn't returning any errors when uploading the fields.
