### ISSUE TITLE
FIx - Registration's URL Input Field not coming back to valid state

### ISSUE THREAD

**Issue by eduramme** [blockful-io/external-resolver-dapp#129]
How to reproduce:
In the step "Customize Profile", input an invalid URL and try to click "Next", the field will be considered invalid and you will not be able to move to the next step. Fix it to a valid URL, the border of the field will continue red, but you'll be able to move to the next step.

![Image](https://github.com/user-attachments/assets/853aaa84-a1fe-472b-98e0-9ada0ffdce99)

[Stackoverflow answer for regex](https://stackoverflow.com/questions/3809401/what-is-a-good-regular-expression-to-match-a-url)

**Comment by alextnetto** [comment]
Notes for QA: If I input "https://www.empiric.observer" which is a valid domain, isn't showing as valid in the current dev branch, maybe this PR will fix it.

**Comment by alextnetto** [comment]
QA test that didn't passed:
- https://x.com/
- https://www.empiric.observer

These are valid websites that are shown as invalid.

There is also no need for the string "invalid URL", the only action needed is the border becoming red or not.
