### ISSUE TITLE
feat: list subdomains

### ISSUE THREAD

**Issue by alextnetto** [blockful-io/external-resolver-dapp#149]
### List a domain's subdomains list

With the usage of [ENSIP-16 v2](https://discuss.ens.domains/t/ensip-16-v2-metadata-api-improvements/19500) we are able to query the subdomains of a domain.

The goal of this issue is to create a table of subdomains and include it in the "Subdomains" tab content.

![Image](https://github.com/user-attachments/assets/b547a6fa-bc49-4b3a-b615-4e2cbacf573b)

### Constraints
- It is possible that either a domain has no subdomains _or_ a domain's resolver is not in alignment with subdomains querying rules, meaning that it won't be able to inform this domain's subdomains. In both cases, we should display messages to the visitors.

### What should not be done for now?
- Let's not implement search or pagination for the table;
- No action should be done in a subdomain click;

**Comment by FrancoAguzzi** [comment]
@alextnetto 

1. Should a subdomains list be displayed for a domain that doesn't have Database Resolver set as domain's resolver?

**Comment by alextnetto** [comment]
1. For now, we should only list subdomains for domains that use a resolver that is ENSIP-16 compliant, meaning a resolver that has metadata() function and returns a graphQL endpoint. This can work with Database resolvers or L2 resolver, its the same interface.

@FrancoAguzzi Could you also create and specify cards for the items on "What should not be done for now?", please? Much appreciated.
