### ISSUE TITLE
feat: Create Field for Profile Picture in Text Records

### ISSUE THREAD

**Issue by eduramme** [blockful-io/external-resolver-dapp#154]
### Describe the Feature Request

A new field needs to be created in the text records section to allow users to upload and display a profile picture. This feature will enhance the user profile by including a visual representation alongside the text records.

### Requirements

- [x] Add a new field in the text records section specifically for uploading a profile picture.
- [x] Ensure that  the uploaded profile picture is displayed correctly on the user profile page.

### Additional Information
The profile picture field should be optional, but if provided, it should be prominently displayed on the user’s profile.

**Comment by pikonha** [comment]
LGMT ✅
