### ISSUE TITLE
feat: create new subdomain flow (DB resolver)

### ISSUE THREAD

**Issue by eduramme** [blockful-io/external-resolver-dapp#170]
### Describe the Feature Request

Create the modal user-flow for registering a subdomain (with records). 

Figma designs and prototype is available [here](https://www.figma.com/design/zkL15TsNWgrCVxi30WflqA/Domain-Resolver-(ENS-dapp)?node-id=8322-6956&t=XtGwcW1qOucuPaKd-4).

![Image](https://github.com/user-attachments/assets/7ccfe10f-6c61-41c1-883e-bbab75677983)

### Must:
This modal user-flow should only be reachable when a domain uses our new ENSIP for Off-Chain resolvers, meaning that subdomains should not be created through SubGraph.

### Definition of Done:
This issue will be considered as done when:

- [x] All the subdomain registration steps inside the modal, are accessible and have clear rules for accessing (e.g. we cannot let a user access the blockchain call step if the user has put an invalid Ethereum Address)
- [x] Records data are being validated before subdomain registration (please reuse the validations we do in Edit Records Modal, here)

### Other info

- 2 transactions will be made. One for registry and another one for text records

**Comment by pikonha** [comment]
a single transaction has been used to register a subdomain thanks to the EIP-5559 v2
