### ISSUE TITLE
bug: optimize Subdomains setting modal UI

### ISSUE THREAD

**Issue by FrancoAguzzi** [blockful-io/external-resolver-dapp#177]
# Feature Request

In this modal we should update:

- [x] Congrats step alignment
- [x] Gray part of subdomain setting should have limited width (I suggest 50% of the full modal width)

## QA Replication steps

- [ ] Register a subdomain and find the screens shared

## Images

![Image](https://github.com/user-attachments/assets/6ccbf3e6-dcc5-4860-b942-be256dddf0f3)
![Image](https://github.com/user-attachments/assets/1d391c0a-d978-42ac-a9f8-1cf3dc2fad8d)

**Comment by pikonha** [comment]
![Image](https://github.com/user-attachments/assets/a2f9b97d-2c9d-4bf2-b903-6aabf43fe768)

![Image](https://github.com/user-attachments/assets/9c88d6fa-d6a4-49c9-95d3-94f290b9c08c)

LGTM ✅
