### ISSUE TITLE
feat: Add Support for Arbitrum and Arbitrum Sepolia

### ISSUE THREAD

**Issue by FrancoAguzzi** [blockful-io/external-resolver-dapp#191]
### Describe the Feature Request

We want to give ENS community the ability to register domains resolver and domain's subdomains in L2s and our first step towards this goal is enabling Arbitrum connection in **nameful** dApp.

### Preferred Solution

- [ ] Update `wallet-config.tsx` to include Arbitrum and Arbitrum Sepolia networks;
- [ ] Update supported networks enum to include these new networks;
- [ ] Whenever not in a registered network, the user shall be redirected to `/not-supported` page;

### Definition of Done

- [x] Whenever the user is not connected to a supported network, they will be informed that they are not connected. The supported networks shall include Ethereum Mainnet, Ethereum Sepolia, Arbitrum Mainnet, and Arbitrum Sepolia.

### Related Code

`wallet-config.ts`

**Comment by FrancoAguzzi** [comment]
Note: this issue is blocked by a [L2 metadata API](https://github.com/blockful-io/external-resolver/issues/209) that needs to be available in order to access Arbitrum Sepolia data

**Comment by pikonha** [comment]
LGTM 🔥
