### ISSUE TITLE
feat: Update the testnet banner to display when the user is on the Arbitrum testnet as well

### ISSUE THREAD

**Issue by FrancoAguzzi** [blockful-io/external-resolver-dapp#192]
### Describe the Feature Request

The goal of this issue is to ensure the testnet banner is displayed when users are connected to Arbitrum Sepolia, in addition to Ethereum Sepolia.

### Describe Preferred Solution

- Update the condition that displays the banner

### Definition of Done

- [ ] The testnet banner should be displayed when the user is connected to either the Arbitrum testnet or the Ethereum testnet

### Related Code

`TestnetBanner.tsx`

**Comment by guilhermebins** [comment]
Hey, I'd like to contribute to this project. I have a commit for this issue. But I'm not have access to git push. How could I contribute to the project?

**Comment by eduramme** [comment]
@guilhermebins Nice! It's yours

You can contribute by creating a fork and submitting a pull request. I see that you've already done it 🙂
