### ISSUE TITLE
feat: ensure records getting are working fine for Arbitrum resolver

### ISSUE THREAD

**Issue by FrancoAguzzi** [blockful-io/external-resolver-dapp#196]
### Describe the Feature Request

As we are introducing Arbitrum resolvers, we want to guarantee that Arbitrum stored domains datas are safely get by our dApp.

### Definition of done

1. Register a name with Arbitrum resolver and set text records to it: check if text records are get correctly after;
2. Use the previous registered name to create subdomains with Arbitrum resolver: check if subdomain is included in subdomains list;

**Comment by FrancoAguzzi** [comment]
This issue is blocked by [L2 Metadata API](https://github.com/blockful-io/external-resolver/issues/209)

**Comment by pikonha** [comment]
duplicated by #198
