### ISSUE TITLE
feat: Register name with Arbitrum Sepolia resolver

### ISSUE THREAD

**Issue by eduramme** [blockful-io/external-resolver-dapp#197]
### Describe the Feature Request

As part of integrating Arbitrum into the dApp, the goal of this issue is to create and enable `Arbitrum Sepolia Resolver CTA` in the name registration process, specifically during the resolver selection step.

<img width="560" alt="Captura de Tela 2024-09-23 às 13 42 39" src="https://github.com/user-attachments/assets/d3bd93cf-c738-4f55-bec4-262accb399fb">

### Preferred Solution

- The `Arbitrum Sepolia` resolver radio button should appear consistent with the other enabled options, differing only in its icon and label.
- Update the ENS resolver list to include the `Arbitrum Sepolia` resolver and its address.
- When the user reaches the point of registering records for the newly registered domain, prompt them to switch their network to `Arbitrum Sepolia` to confirm the text records transaction. If they are not on `Arbitrum Sepolia`, the transaction should return an error.
- Verify that the `Arbitrum Sepolia` resolver is successfully set after a name registration.

### Definition of Done

- [ ] The `Arbitrum Sepolia` resolver radio button should appear consistent with the other enabled options, differing only in its icon and label.
- [ ] Users can successfully register a name with `Arbitrum Sepolia` resolver, the domain should be created on `ETH Sepolia`.
- [ ] Clear errors should be provided if the process fails due to chain misconfiguration or unsupported chain.
- [ ] The new domain should be accessible.
- [ ] The correct text records, expiration date, and address should be displayed after registration.

### Related Code

`ENSResolverComponent.tsx`

**Comment by pikonha** [comment]
moving back to ideas because the registering of 2LD is not supported yet. we need to figure out a flow of registering the 2LD on both the L1 and L2
