### ISSUE TITLE
feat: Set Text Records via Arbitrum Sepolia

### ISSUE THREAD

**Issue by eduramme** [blockful-io/external-resolver-dapp#198]
### Describe the Feature Request

The goal of this issue is to enable users to edit text records for a domain using the `Arbitrum Sepolia` Resolver directly from the domain page. This will allow users to update their text records when they are connected to the Arbitrum Sepolia network.

### Describe Preferred Solution

The preferred solution is to reuse the existing Edit Records modal. When it's an Arbitrum Sepolia resolver, prompt the user to switch their connected network to Arbitrum Sepolia (via a wallet request). This will enable the user to set new records for their domains using the Arbitrum Sepolia resolver.

### Definition of Done

- [ ]  Successfully update the text records for a domain using the Arbitrum Sepolia resolver through the Edit Records modal.

### Related Code

`EditModalContent.tsx`

**Comment by pikonha** [comment]
setting records of a subdomain of `arb.eth`

**Comment by pikonha** [comment]
blocked by L1Resolver multicall @pikonha

**Comment by pikonha** [comment]
Definition of done

* Register a name with Arbitrum resolver and set text records to it: check if text records are get correctly after;
* Use the previous registered name to create subdomains with Arbitrum resolver: check if subdomain is included in subdomains list;
