### ISSUE TITLE
feat: Enable contentHash Record

### ISSUE THREAD

**Issue by eduramme** [blockful-io/external-resolver-dapp#209]
Add support for managing contentHash records in ENS. Users should be able to retrieve and update the contentHash associated with their ENS domains.

Tasks:

- [x] Implement retrieval of contentHash records.
- [x] Add functionality to update contentHash records.

https://www.figma.com/design/zkL15TsNWgrCVxi30WflqA/Domain-Resolver-(ENS-dapp)?node-id=1726-6740&node-type=canvas&t=loxlkSAXEePLnloZ-0

![Image](https://github.com/user-attachments/assets/7c5c189e-d1ff-4b88-a829-6e06368509e0)

**Comment by pikonha** [comment]
[in here](https://etherscan.io/address/0x231b0Ee14048e9dCcD1d247744d114a4EB5E8E63#code#F16#L16) you can find the `setContenthash` function signature you need to call in order to set the contenthash of a given domain

**Comment by pikonha** [comment]
unblocked by #161

**Comment by pikonha** [comment]
[client usage ](https://github.com/blockful-io/external-resolver/pull/228/files#diff-1220c9a5f35edf8404589c0f4ab9587b912bf9456f043ed88cb411b0d2ec12ccR82)

**Comment by pikonha** [comment]
seems to be working fine both the read and write on db and only the write on the arb domains, which is a known problem on our Arbitrum CCIP-Read implementation.
