### ISSUE TITLE
feat: Standardize Database and L2 Calls

### ISSUE THREAD

**Issue by eduramme** [blockful-io/external-resolver-dapp#211]
Currently, the database and Layer 2 (L2) calls do not follow a consistent standard. This can lead to difficulties in maintaining and reading the code, as well as potential performance and scalability issues.

### Describe Preferred Solution

- Analyze the current database and L2 calls to identify inconsistencies and areas for improvement.
- Define a standard for database and L2 calls that is efficient and maintainable.
- Refactor existing calls to adhere to the new standard.
- Document best practices for database and L2 calls in the project to ensure that new developments follow the established guidelines.

**Comment by pikonha** [comment]
QA Notes:

* [x] DB subdomain register
* [ ] Arb subdomain register
  * still ask for adding the `Arbitrum Sepolia` on the Metamask when it already has
  ![Image](https://github.com/user-attachments/assets/0b99bbfe-d4f1-4a8f-a3a7-58b5f4049498)
  ![Image](https://github.com/user-attachments/assets/300c7f14-65e4-44ec-8380-74f5b4346580)
  * I'm unable to register a subdomain on the L2
  ![Image](https://github.com/user-attachments/assets/ea748325-8827-4596-ae18-2d49d5624afd)

**Comment by pikonha** [comment]
seems to be working now
