### ISSUE TITLE
feat: Error Toast Not Displayed Correctly When Modal is Open

### ISSUE THREAD

**Issue by eduramme** [blockful-io/external-resolver-dapp#218]
## Bug Report

When a modal is open, the error toast notification is not displayed correctly (e.g., behind the modal, not visible). This prevents users from seeing critical error messages while interacting with modals.

### Acceptance Criteria:

- [x] The error toast should be clearly visible when a modal is open.

**Comment by pikonha** [comment]
![Image](https://github.com/user-attachments/assets/ea6242a1-e502-4264-9785-b05ee73b56d2)

seems good on the scenario I've tested, are there any other replication steps?

**Comment by eduramme** [comment]
@pikonha nop, that's it 🙂

**Comment by pikonha** [comment]
then I approve ✅
