### ISSUE TITLE
fix: profile page is fetching sepolia data without a wallet connected

### ISSUE THREAD

**Issue by eduramme** [blockful-io/external-resolver-dapp#232]
## Bug Report
![Image](https://github.com/user-attachments/assets/2fcc3968-9a28-441e-b9e3-3015fe846bb1)

### Related code

```sh
insert short code snippets here
```

**Comment by pikonha** [comment]
what is that about? what's the expected behavior?

**Comment by eduramme** [comment]
@pikonha When you fetch a profile without a wallet connected, te dApp should retrieve data from eth mainnet instead of sepolia.

It was previously retrieving data from sepolia, now it's retrieving data from mainnet (by default)

**Comment by pikonha** [comment]
LGTM
