### ISSUE TITLE
Unable to Register 3 or 4 Letter Domains

### ISSUE THREAD

**Issue by eduramme** [blockful-io/external-resolver-dapp#78]
### Description
There is an issue when attempting to register domains that are 3 or 4 letters long. The blockchain system returns an error during the registration process for these specific domain lengths. This is probably related to cost estimation

### Steps to Reproduce

1. Navigate to the domain registration page.
2. Enter a domain name that is either 3 or 4 letters long.
3. Attempt to complete the registration process.

### **Expected Result**
The domain registration process should complete successfully, allowing users to register 3 or 4 letter domains.

### **Actual Result**
An error message is displayed, and the domain registration fails for 3 or 4 letter domains.

### Error Message
https://sepolia.etherscan.io/tx/0xf854f38268c7d4462fa4522215f5b4ff68604602be36c27bccb19387664f9938

![Image](https://github.com/user-attachments/assets/e63fc5d1-61bd-4f15-82c0-f8f97940c538)

![Image](https://github.com/user-attachments/assets/d7eea692-9fec-4818-9ace-29d624d6ce78)

### Impact
This issue prevents users from registering short domains, which may be crucial for branding and other purposes.
### Possible Causes
This issue is likely related to the cost estimation process for domain registration.

### Suggested Solution

- Investigate the domain validation logic in the blockchain registration process.
- Verify if there are any restrictions or bugs specifically related to the length of the domain names.
- Adjust the code to allow registration of 3 or 4 letter domains without errors.

**Comment by eduramme** [comment]
@lgahdl https://docs.ens.domains/registry/eth

**Comment by alextnetto** [comment]
Niceee, just registered alek.eth 😎
