### ISSUE TITLE
Add more address types

### ISSUE THREAD

**Issue by alextnetto** [blockful-io/external-resolver-dapp#87]
Add more address options: BTC, Optimism, Arbitrum, Polygon.

![Image](https://github.com/user-attachments/assets/97ba3448-2360-41dd-b974-378173a076e0)

[Docs](https://docs.ens.domains/ensip/9)

Feature is valid when BTC address is shown on [ENS dApp Sepolia](https://app.ens.domains/)

**Comment by lgahdl** [comment]
Found out that the Coin Type numbers change(at least for Sepolia Applications):

ETH - 60
BTC - 0
Optimistic ETH - 2147483658
ARB - 2147525809
MATIC (Polygon) - 2147483658
