### ISSUE TITLE
refactor: align button for next step

### ISSUE THREAD

**Issue by alextnetto** [blockful-io/external-resolver-dapp#90]
### Describe the Refactor Request

The placement of the button for the next action or page is inconsistent across different steps of our application. This inconsistency disrupts the user experience and reduces cohesion in the interface. We need to standardize the location of this button to improve navigation and overall UX.

### Describe Preferred Solution

Implement a consistent layout where the "next" button is placed in the same location across all steps of the application. This solution should:

1. Identify a standard position for the button (e.g., bottom right corner) that works well for all steps.
2. Ensure the button's size, style, and general appearance remain consistent throughout.
3. Adjust layouts of existing steps to accommodate this standardized button placement without disrupting other content.
4. Maintain this consistency across different device sizes and orientations.

**Comment by alextnetto** [comment]
@lgahdl In the steps that require wallet interaction, the button "Connect Metamask" is in a different position than "next." The expected behavior is being able to move forward in the process without moving the mouse, so the buttons should be in the same position.

**Comment by lgahdl** [comment]
> [@lgahdl](https://github.com/lgahdl) In the steps that require wallet interaction, the button "Connect Metamask" is in a different position than "next." The expected behavior is being able to move forward in the process without moving the mouse, so the buttons should be in the same position.

Makes sense, already fixed the position of the wallet interaction and "View Domain" buttons, will open the PR again, thanks for the review!

**Comment by alextnetto** [comment]
Nicee, much better UX with this card finished. Thanks @lgahdl!
