### ISSUE TITLE
feat: show current records when editing

### ISSUE THREAD

**Issue by alextnetto** [blockful-io/external-resolver-dapp#91]
### Describe the Feature Request

Our application currently doesn't display existing ENS domain records when users are editing them. This limitation forces users to recreate records from scratch, which is inefficient and prone to errors. We need to implement a feature that shows the current records and allows users to edit them directly.

Current records.
<img src="https://github.com/user-attachments/assets/c8422b91-16c2-442c-814d-b2ca32cc22ca" alt="Image" height="300">
Editing records, but without current values.
<img src="https://github.com/user-attachments/assets/1ccf6d0f-067e-4b91-9b1a-f101c0c9cd3b" alt="Image" height="300">

### Describe Preferred Solution

Implement a feature that retrieves and displays existing ENS domain records when a user initiates the editing process. The solution should:

1. Fetch current ENS records for the domain being edited.
2. Pre-populate the editing interface with these existing records.
3. Allow users to modify, add, or remove records.
4. Provide clear visual cues to distinguish between existing records and new/modified ones.
5. Implement a save mechanism that updates only the changed records.

**Comment by eduramme** [comment]
@alextnetto **FYI** We have found a bug that requires a bigger scope. I will open a new issue to address it. https://github.com/blockful-io/external-resolver-dapp/pull/97#pullrequestreview-2199693849

**Comment by alextnetto** [comment]
@lgahdl @eduramme, great work and team job!
